# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - master

pool:
    vmImage: "ubuntu-16.04"

strategy:
    matrix:
        node_8_x:
            node_version: 8.x
        node_9_x:
            node_version: 9.x
        node_10_x:
            node_version: 10.x
        node_11_x:
            node_version: 11.x

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: $(node_version)

    - script: |
          npm install
          npm test
          npm alex
      displayName: "npm install, test, and Alex lint"
